spring:
  cloud:
    gateway:
      routes:
        - id: ms-customer
          uri: http://localhost:8080
          predicates:
            - Path=/v1/customer/**
        - id: ms-order
          uri: http://localhost:8081
          predicates:
            - Path=/v1/order/**
