server:
  port: 8761  #bu eureka nin default portudur

eureka:
  client:
    register-with-eureka: false # bu config eureka serverinin ozunu qeydiyyatdan kecmemesini temin edir
    fetch-registry: false  # bu config eureka serverinin basqa eureka serverlerinden qeydiyyat melumatlarini cekmemesini temin edir