spring:
  # Database
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-customer
    username: postgres
    password: "012345"
    driver-class-name: org.postgresql.Driver
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: create # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
